wget -c http://learnsanskrit.net/sanskritserver/mp3/a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/aa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/i.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ii.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/u.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/uu.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/r2.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/r3.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/l2.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/e.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ai.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/o.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/au.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/aM.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/aH.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/k1a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/kha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ga.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/gha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/GNa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ca.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/cha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ja.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/jha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/JNa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/t2a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/t2ha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/d2a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/d2ha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/n3a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ta.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/tha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/da.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/dha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/na.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/pa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/pha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ba.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/bha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ma.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ya.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ra.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/la.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/va.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/sha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/s2a.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/sa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/ha.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/jJNa.mp3
wget -c http://learnsanskrit.net/sanskritserver/mp3/kSha.mp3
